[phases.setup]
cmds = [
    "pip install --upgrade pip",
    "pip install torch --index-url https://download.pytorch.org/whl/cpu",
    "pip install -r requirements.txt"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install torch --index-url https://download.pytorch.org/whl/cpu",
    "pip install -r requirements.txt"
]

[start]
cmd = "python english_bot.py"
